### ISSUE TITLE
Sample Implementation

### ISSUE THREAD

**Issue by sagarsys** [FlyingDR/gulp-icomoon-converter#1]
Hello,

Can you provide a sample implementation of the plugin in your readme? I think it would be quite helpful for a lot of people. Right now, based on the available documentation, it's not clear how to implement this module in my gulp file.

Thanks.

**Comment by FlyingDR** [comment]
Your issue turns into almost complete rewrite of the plugin :) But is brings much more flexibility, so thank you for it! 

Hope you will like this [example](https://github.com/FlyingDR/gulp-icomoon-converter/tree/master/example) and new documentation.

**Comment by sagarsys** [comment]
Thanks for the nifty example, it's now more clear about possible implementations! I will definitely give it a go in another project! Keep up the good work!
